import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.whyChoose": "Why Choose Us",
    "nav.contact": "Contact",
    "nav.getInTouch": "Get in Touch",
    "nav.labName": "Medical Lab",
    "nav.tagline": "Precision Diagnostics",

    // Hero Section
    "hero.badge": "Trusted Medical Diagnostics",
    "hero.title": "Precision Lab Results You Can",
    "hero.titleHighlight": "Trust",
    "hero.description": "State-of-the-art medical laboratory services in Amman, Jordan. We combine advanced technology with expert care to deliver accurate diagnostic results for your health needs.",
    "hero.viewServices": "View Our Services",
    "hero.contactUs": "Contact Us",
    "hero.fastResults": "Fast Results",
    "hero.fastResultsSub": "24-48 Hours",
    "hero.certifiedLab": "Certified Lab",
    "hero.certifiedLabSub": "ISO Accredited",
    "hero.expertTeam": "Expert Team",
    "hero.expertTeamSub": "15+ Years",

    // Services Preview
    "services.badge": "Our Services",
    "services.title": "Comprehensive Laboratory Services",
    "services.description": "We offer a wide range of diagnostic tests using advanced technology and performed by experienced professionals.",
    "services.viewAll": "View All Services",
    "services.bloodTests": "Blood Tests",
    "services.bloodTestsDesc": "Complete blood count, blood chemistry, and comprehensive panels for thorough health assessment.",
    "services.hormoneAnalysis": "Hormone Analysis",
    "services.hormoneAnalysisDesc": "Thyroid function, reproductive hormones, and metabolic hormone testing with precision.",
    "services.diabetesScreening": "Diabetes Screening",
    "services.diabetesScreeningDesc": "Glucose testing, HbA1c monitoring, and insulin level assessments for diabetes management.",
    "services.pcrTesting": "PCR Testing",
    "services.pcrTestingDesc": "Advanced molecular diagnostics for infectious diseases and genetic testing.",
    "services.pathology": "Pathology",
    "services.pathologyDesc": "Tissue analysis, cytology, and histopathology services for accurate diagnosis.",
    "services.generalDiagnostics": "General Diagnostics",
    "services.generalDiagnosticsDesc": "Urinalysis, stool tests, and other routine laboratory examinations.",

    // Why Choose Preview
    "whyChoose.badge": "Why Choose Us",
    "whyChoose.title": "Trusted by Thousands of Patients Across Jordan",
    "whyChoose.description": "Our commitment to excellence, accuracy, and patient care has made us one of the most trusted medical laboratories in Amman. We combine state-of-the-art technology with experienced professionals.",
    "whyChoose.learnMore": "Learn More About Us",
    "whyChoose.accredited": "Accredited Laboratory",
    "whyChoose.accreditedDesc": "ISO certified with international quality standards",
    "whyChoose.quickTurnaround": "Quick Turnaround",
    "whyChoose.quickTurnaroundDesc": "Most results available within 24-48 hours",
    "whyChoose.expertPathologists": "Expert Pathologists",
    "whyChoose.expertPathologistsDesc": "Board-certified specialists with years of experience",
    "whyChoose.patientCentered": "Patient-Centered Care",
    "whyChoose.patientCenteredDesc": "Comfortable environment with compassionate staff",
    "whyChoose.yearsExperience": "Years Experience",
    "whyChoose.testsPerYear": "Tests Per Year",
    "whyChoose.testTypes": "Test Types",
    "whyChoose.accuracyRate": "Accuracy Rate",
    "whyChoose.commitment": "Committed to accuracy and patient satisfaction",

    // CTA Section
    "cta.title": "Need a Lab Test?",
    "cta.titleLine2": "We're Here to Help",
    "cta.description": "Visit our laboratory in Amman or contact us to learn more about our services. Our friendly staff is ready to assist you with your diagnostic needs.",
    "cta.callUs": "Call Us Now",
    "cta.contactUs": "Contact Us",
    "cta.address": "123 Medical District, Amman, Jordan",

    // Footer
    "footer.description": "Your trusted partner for accurate medical diagnostics and laboratory services in Jordan.",
    "footer.quickLinks": "Quick Links",
    "footer.ourServices": "Our Services",
    "footer.contactUs": "Contact Us",
    "footer.copyright": "Medical Lab Name. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.hours1": "Sat - Thu: 7:00 AM - 9:00 PM",
    "footer.hours2": "Friday: 8:00 AM - 2:00 PM",

    // About Page
    "about.badge": "About Us",
    "about.title": "Your Trusted Partner in Medical Diagnostics",
    "about.intro": "For over 15 years, Medical Lab Name has been providing accurate, reliable laboratory services to healthcare providers and patients across Jordan.",
    "about.storyBadge": "Our Story",
    "about.storyTitle": "A Legacy of Excellence in Healthcare",
    "about.storyP1": "Founded in 2008, Medical Lab Name began with a simple mission: to provide the most accurate and accessible laboratory services to the people of Jordan.",
    "about.storyP2": "Over the years, we have grown from a small facility to a comprehensive diagnostic center equipped with state-of-the-art technology and staffed by highly qualified professionals.",
    "about.storyP3": "Today, we serve thousands of patients annually, partnering with hospitals, clinics, and healthcare providers throughout Amman and beyond. Our commitment to quality and patient care remains at the heart of everything we do.",
    "about.modernFacility": "Modern Facility",
    "about.modernFacilityDesc": "State-of-the-art equipment",
    "about.expertTeam": "Expert Team",
    "about.expertTeamDesc": "Certified pathologists & technicians",
    "about.isoCertified": "ISO Certified",
    "about.isoCertifiedDesc": "International quality standards",
    "about.missionTitle": "Our Mission",
    "about.missionText": "To deliver accurate, timely, and affordable laboratory services that empower healthcare providers and patients to make informed medical decisions. We are committed to maintaining the highest standards of quality while ensuring accessible care for all.",
    "about.visionTitle": "Our Vision",
    "about.visionText": "To be the leading medical laboratory in Jordan, recognized for our commitment to excellence, innovation, and patient-centered care. We envision a future where every individual has access to world-class diagnostic services.",
    "about.valuesBadge": "Our Values",
    "about.valuesTitle": "What Drives Us Every Day",
    "about.valuesDesc": "These core values guide our work and define who we are as an organization.",
    "about.accuracy": "Accuracy",
    "about.accuracyDesc": "We maintain the highest standards of precision in every test we perform.",
    "about.patientCare": "Patient Care",
    "about.patientCareDesc": "Your comfort and well-being are at the center of everything we do.",
    "about.timeliness": "Timeliness",
    "about.timelinessDesc": "We understand the importance of quick results and work efficiently.",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "Continuous improvement and adherence to international standards.",

    // Services Page
    "servicesPage.badge": "Our Services",
    "servicesPage.title": "Comprehensive Laboratory Services",
    "servicesPage.description": "We offer a wide range of diagnostic tests using state-of-the-art equipment and performed by experienced laboratory professionals.",
    "servicesPage.processBadge": "Simple Process",
    "servicesPage.processTitle": "How It Works",
    "servicesPage.processDesc": "Getting tested is quick and easy. Here's what to expect.",
    "servicesPage.step1": "Visit Our Lab",
    "servicesPage.step1Desc": "Walk in or make an appointment at our facility",
    "servicesPage.step2": "Sample Collection",
    "servicesPage.step2Desc": "Our trained staff will collect your samples",
    "servicesPage.step3": "Lab Analysis",
    "servicesPage.step3Desc": "Your samples are analyzed using advanced equipment",
    "servicesPage.step4": "Get Results",
    "servicesPage.step4Desc": "Receive accurate results within 24-48 hours",
    "servicesPage.cbc": "Complete Blood Count (CBC)",
    "servicesPage.cbcDesc": "Comprehensive analysis of blood cells including red blood cells, white blood cells, and platelets. Essential for detecting infections, anemia, and other conditions.",
    "servicesPage.hormones": "Hormone Analysis",
    "servicesPage.hormonesDesc": "Detailed hormone level testing to assess thyroid function, reproductive health, and metabolic disorders.",
    "servicesPage.diabetes": "Diabetes & Metabolic Testing",
    "servicesPage.diabetesDesc": "Comprehensive diabetes screening and monitoring including glucose levels and long-term blood sugar control.",
    "servicesPage.pcr": "PCR & Molecular Diagnostics",
    "servicesPage.pcrDesc": "Advanced molecular testing using PCR technology for accurate detection of infectious diseases and genetic markers.",
    "servicesPage.pathology": "Pathology & Histology",
    "servicesPage.pathologyDesc": "Expert analysis of tissue samples and cells for accurate diagnosis of diseases including cancer screening.",
    "servicesPage.urinalysis": "Urinalysis & Stool Tests",
    "servicesPage.urinalysisDesc": "Routine and comprehensive analysis of urine and stool samples for kidney function, infections, and digestive health.",
    "servicesPage.immunology": "Immunology & Serology",
    "servicesPage.immunologyDesc": "Testing for immune system function, allergies, and autoimmune conditions.",
    "servicesPage.prenatal": "Prenatal Screening",
    "servicesPage.prenatalDesc": "Comprehensive testing for expectant mothers to ensure healthy pregnancy outcomes.",
    "servicesPage.drugMonitoring": "Drug Monitoring",
    "servicesPage.drugMonitoringDesc": "Therapeutic drug monitoring and toxicology screening for medication management and safety.",
    "servicesPage.chemistry": "Chemistry Panel",
    "servicesPage.chemistryDesc": "Comprehensive metabolic panel to assess organ function and overall health status.",

    // Why Choose Us Page
    "whyPage.badge": "Why Choose Us",
    "whyPage.title": "Excellence in Every Test",
    "whyPage.description": "Discover why thousands of patients and healthcare providers in Jordan trust Medical Lab Name for their diagnostic needs.",
    "whyPage.isoAccredited": "ISO Accredited Laboratory",
    "whyPage.isoAccreditedDesc": "Our laboratory meets international quality standards, ensuring reliable and accurate results you can trust.",
    "whyPage.fastTurnaround": "Fast Turnaround Time",
    "whyPage.fastTurnaroundDesc": "Most test results are available within 24-48 hours, helping you and your healthcare provider make timely decisions.",
    "whyPage.expertTeam": "Expert Medical Team",
    "whyPage.expertTeamDesc": "Board-certified pathologists and experienced laboratory technicians with years of expertise in diagnostic testing.",
    "whyPage.advancedTech": "Advanced Technology",
    "whyPage.advancedTechDesc": "State-of-the-art diagnostic equipment and automated systems ensure precise and consistent results.",
    "whyPage.patientCentered": "Patient-Centered Care",
    "whyPage.patientCenteredDesc": "A comfortable, welcoming environment with compassionate staff dedicated to your well-being.",
    "whyPage.experience": "15+ Years of Experience",
    "whyPage.experienceDesc": "Over a decade of trusted service to patients and healthcare providers across Jordan.",
    "whyPage.yearsExp": "Years of Experience",
    "whyPage.testsYear": "Tests Per Year",
    "whyPage.testTypes": "Test Types Available",
    "whyPage.satisfaction": "Patient Satisfaction",
    "whyPage.commitmentBadge": "Our Commitment",
    "whyPage.commitmentTitle": "Your Health is Our Priority",
    "whyPage.commitmentDesc": "At Medical Lab Name, we go beyond just providing test results. We're committed to supporting your healthcare journey with excellence at every step.",
    "whyPage.commitment1": "Accuracy guaranteed with quality control protocols",
    "whyPage.commitment2": "Confidential handling of all patient information",
    "whyPage.commitment3": "Affordable pricing with transparent costs",
    "whyPage.commitment4": "Convenient location in central Amman",
    "whyPage.commitment5": "Extended operating hours for your convenience",
    "whyPage.commitment6": "Partnership with leading healthcare providers",
    "whyPage.visitTitle": "Visit Us Today",
    "whyPage.location": "Location",
    "whyPage.workingHours": "Working Hours",
    "whyPage.workingHoursVal": "Sat-Thu: 7AM-9PM | Fri: 8AM-2PM",

    // Contact Page
    "contact.badge": "Contact Us",
    "contact.title": "Get in Touch",
    "contact.description": "Have questions about our services? We're here to help. Reach out to us through any of the channels below.",
    "contact.infoTitle": "Contact Information",
    "contact.address": "Address",
    "contact.addressLine1": "123 Medical District",
    "contact.addressLine2": "Amman, Jordan",
    "contact.phone": "Phone",
    "contact.phoneAvailable": "Available during working hours",
    "contact.email": "Email",
    "contact.emailResponse": "We respond within 24 hours",
    "contact.workingHours": "Working Hours",
    "contact.hours1": "Saturday - Thursday: 7:00 AM - 9:00 PM",
    "contact.hours2": "Friday: 8:00 AM - 2:00 PM",
    "contact.mapTitle": "Map Location",
    "contact.formTitle": "Send us a Message",
    "contact.formDesc": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.fullName": "Full Name",
    "contact.fullNamePlaceholder": "Enter your full name",
    "contact.emailAddress": "Email Address",
    "contact.emailPlaceholder": "Enter your email address",
    "contact.phoneNumber": "Phone Number",
    "contact.phonePlaceholder": "Enter your phone number",
    "contact.message": "Message",
    "contact.messagePlaceholder": "How can we help you?",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.privacy": "We respect your privacy and never share your information.",
    "contact.successTitle": "Message Sent!",
    "contact.successDesc": "Thank you for contacting us. We'll get back to you soon.",
  },
  ar: {
    // Navbar
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.whyChoose": "لماذا نحن",
    "nav.contact": "اتصل بنا",
    "nav.getInTouch": "تواصل معنا",
    "nav.labName": "المختبر الطبي",
    "nav.tagline": "تشخيص دقيق",

    // Hero Section
    "hero.badge": "تشخيصات طبية موثوقة",
    "hero.title": "نتائج مخبرية دقيقة يمكنك",
    "hero.titleHighlight": "الوثوق بها",
    "hero.description": "خدمات مخبرية طبية متطورة في عمان، الأردن. نجمع بين التكنولوجيا المتقدمة والرعاية المتخصصة لتقديم نتائج تشخيصية دقيقة لاحتياجاتك الصحية.",
    "hero.viewServices": "عرض خدماتنا",
    "hero.contactUs": "اتصل بنا",
    "hero.fastResults": "نتائج سريعة",
    "hero.fastResultsSub": "24-48 ساعة",
    "hero.certifiedLab": "مختبر معتمد",
    "hero.certifiedLabSub": "معتمد من ISO",
    "hero.expertTeam": "فريق خبير",
    "hero.expertTeamSub": "+15 سنة",

    // Services Preview
    "services.badge": "خدماتنا",
    "services.title": "خدمات مخبرية شاملة",
    "services.description": "نقدم مجموعة واسعة من الفحوصات التشخيصية باستخدام تقنيات متطورة ويقوم بها متخصصون ذوو خبرة.",
    "services.viewAll": "عرض جميع الخدمات",
    "services.bloodTests": "فحوصات الدم",
    "services.bloodTestsDesc": "تعداد الدم الكامل، كيمياء الدم، والفحوصات الشاملة لتقييم صحي دقيق.",
    "services.hormoneAnalysis": "تحليل الهرمونات",
    "services.hormoneAnalysisDesc": "وظائف الغدة الدرقية، الهرمونات التناسلية، وفحص الهرمونات الاستقلابية بدقة.",
    "services.diabetesScreening": "فحص السكري",
    "services.diabetesScreeningDesc": "فحص الجلوكوز، مراقبة HbA1c، وتقييم مستويات الأنسولين لإدارة السكري.",
    "services.pcrTesting": "فحص PCR",
    "services.pcrTestingDesc": "تشخيصات جزيئية متقدمة للأمراض المعدية والفحوصات الجينية.",
    "services.pathology": "علم الأمراض",
    "services.pathologyDesc": "تحليل الأنسجة، علم الخلايا، وخدمات الهستوباثولوجي للتشخيص الدقيق.",
    "services.generalDiagnostics": "التشخيصات العامة",
    "services.generalDiagnosticsDesc": "تحليل البول، فحوصات البراز، والفحوصات المخبرية الروتينية الأخرى.",

    // Why Choose Preview
    "whyChoose.badge": "لماذا نحن",
    "whyChoose.title": "موثوق من آلاف المرضى في الأردن",
    "whyChoose.description": "التزامنا بالتميز والدقة ورعاية المرضى جعلنا من أكثر المختبرات الطبية موثوقية في عمان. نجمع بين التكنولوجيا المتطورة والمتخصصين ذوي الخبرة.",
    "whyChoose.learnMore": "اعرف المزيد عنا",
    "whyChoose.accredited": "مختبر معتمد",
    "whyChoose.accreditedDesc": "معتمد من ISO بمعايير جودة عالمية",
    "whyChoose.quickTurnaround": "نتائج سريعة",
    "whyChoose.quickTurnaroundDesc": "معظم النتائج متاحة خلال 24-48 ساعة",
    "whyChoose.expertPathologists": "أخصائيو أمراض خبراء",
    "whyChoose.expertPathologistsDesc": "متخصصون معتمدون بسنوات من الخبرة",
    "whyChoose.patientCentered": "رعاية تركز على المريض",
    "whyChoose.patientCenteredDesc": "بيئة مريحة مع طاقم متعاطف",
    "whyChoose.yearsExperience": "سنوات الخبرة",
    "whyChoose.testsPerYear": "فحص سنوياً",
    "whyChoose.testTypes": "نوع فحص",
    "whyChoose.accuracyRate": "نسبة الدقة",
    "whyChoose.commitment": "ملتزمون بالدقة ورضا المرضى",

    // CTA Section
    "cta.title": "هل تحتاج فحص مخبري؟",
    "cta.titleLine2": "نحن هنا لمساعدتك",
    "cta.description": "قم بزيارة مختبرنا في عمان أو تواصل معنا لمعرفة المزيد عن خدماتنا. طاقمنا الودود جاهز لمساعدتك في احتياجاتك التشخيصية.",
    "cta.callUs": "اتصل بنا الآن",
    "cta.contactUs": "تواصل معنا",
    "cta.address": "123 الحي الطبي، عمان، الأردن",

    // Footer
    "footer.description": "شريكك الموثوق للتشخيصات الطبية الدقيقة وخدمات المختبر في الأردن.",
    "footer.quickLinks": "روابط سريعة",
    "footer.ourServices": "خدماتنا",
    "footer.contactUs": "اتصل بنا",
    "footer.copyright": "اسم المختبر الطبي. جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.hours1": "السبت - الخميس: 7:00 ص - 9:00 م",
    "footer.hours2": "الجمعة: 8:00 ص - 2:00 م",

    // About Page
    "about.badge": "من نحن",
    "about.title": "شريكك الموثوق في التشخيصات الطبية",
    "about.intro": "لأكثر من 15 عاماً، يقدم اسم المختبر الطبي خدمات مخبرية دقيقة وموثوقة لمقدمي الرعاية الصحية والمرضى في جميع أنحاء الأردن.",
    "about.storyBadge": "قصتنا",
    "about.storyTitle": "إرث من التميز في الرعاية الصحية",
    "about.storyP1": "تأسس اسم المختبر الطبي في عام 2008 بمهمة بسيطة: تقديم أدق خدمات المختبر وأكثرها سهولة للوصول لأهل الأردن.",
    "about.storyP2": "على مر السنين، نمونا من منشأة صغيرة إلى مركز تشخيصي شامل مجهز بأحدث التقنيات ويعمل به متخصصون مؤهلون تأهيلاً عالياً.",
    "about.storyP3": "اليوم، نخدم آلاف المرضى سنوياً، بالشراكة مع المستشفيات والعيادات ومقدمي الرعاية الصحية في جميع أنحاء عمان وما بعدها. التزامنا بالجودة ورعاية المرضى يبقى في صميم كل ما نقوم به.",
    "about.modernFacility": "منشأة حديثة",
    "about.modernFacilityDesc": "أحدث المعدات",
    "about.expertTeam": "فريق خبير",
    "about.expertTeamDesc": "أخصائيو وفنيو أمراض معتمدون",
    "about.isoCertified": "معتمد من ISO",
    "about.isoCertifiedDesc": "معايير جودة عالمية",
    "about.missionTitle": "مهمتنا",
    "about.missionText": "تقديم خدمات مخبرية دقيقة وسريعة وبأسعار معقولة تمكّن مقدمي الرعاية الصحية والمرضى من اتخاذ قرارات طبية مستنيرة. نحن ملتزمون بالحفاظ على أعلى معايير الجودة مع ضمان رعاية في متناول الجميع.",
    "about.visionTitle": "رؤيتنا",
    "about.visionText": "أن نكون المختبر الطبي الرائد في الأردن، معروفين بالتزامنا بالتميز والابتكار والرعاية التي تركز على المريض. نتصور مستقبلاً يحصل فيه كل فرد على خدمات تشخيصية عالمية المستوى.",
    "about.valuesBadge": "قيمنا",
    "about.valuesTitle": "ما يحركنا كل يوم",
    "about.valuesDesc": "هذه القيم الأساسية توجه عملنا وتحدد هويتنا كمنظمة.",
    "about.accuracy": "الدقة",
    "about.accuracyDesc": "نحافظ على أعلى معايير الدقة في كل فحص نقوم به.",
    "about.patientCare": "رعاية المرضى",
    "about.patientCareDesc": "راحتك ورفاهيتك في صميم كل ما نفعله.",
    "about.timeliness": "الالتزام بالوقت",
    "about.timelinessDesc": "نفهم أهمية النتائج السريعة ونعمل بكفاءة.",
    "about.excellence": "التميز",
    "about.excellenceDesc": "التحسين المستمر والالتزام بالمعايير الدولية.",

    // Services Page
    "servicesPage.badge": "خدماتنا",
    "servicesPage.title": "خدمات مخبرية شاملة",
    "servicesPage.description": "نقدم مجموعة واسعة من الفحوصات التشخيصية باستخدام أحدث المعدات ويقوم بها متخصصون مخبريون ذوو خبرة.",
    "servicesPage.processBadge": "عملية بسيطة",
    "servicesPage.processTitle": "كيف تتم العملية",
    "servicesPage.processDesc": "إجراء الفحص سريع وسهل. إليك ما يمكن توقعه.",
    "servicesPage.step1": "زيارة المختبر",
    "servicesPage.step1Desc": "تعال مباشرة أو احجز موعداً في منشأتنا",
    "servicesPage.step2": "جمع العينات",
    "servicesPage.step2Desc": "سيقوم طاقمنا المدرب بجمع عيناتك",
    "servicesPage.step3": "التحليل المخبري",
    "servicesPage.step3Desc": "يتم تحليل عيناتك باستخدام معدات متطورة",
    "servicesPage.step4": "استلام النتائج",
    "servicesPage.step4Desc": "احصل على نتائج دقيقة خلال 24-48 ساعة",
    "servicesPage.cbc": "تعداد الدم الكامل (CBC)",
    "servicesPage.cbcDesc": "تحليل شامل لخلايا الدم بما في ذلك كريات الدم الحمراء وكريات الدم البيضاء والصفائح الدموية. ضروري للكشف عن العدوى وفقر الدم وحالات أخرى.",
    "servicesPage.hormones": "تحليل الهرمونات",
    "servicesPage.hormonesDesc": "فحص مفصل لمستويات الهرمونات لتقييم وظائف الغدة الدرقية والصحة الإنجابية والاضطرابات الاستقلابية.",
    "servicesPage.diabetes": "فحص السكري والاستقلاب",
    "servicesPage.diabetesDesc": "فحص ومراقبة شاملة للسكري بما في ذلك مستويات الجلوكوز والتحكم طويل الأمد في سكر الدم.",
    "servicesPage.pcr": "PCR والتشخيصات الجزيئية",
    "servicesPage.pcrDesc": "فحوصات جزيئية متقدمة باستخدام تقنية PCR للكشف الدقيق عن الأمراض المعدية والعلامات الجينية.",
    "servicesPage.pathology": "علم الأمراض والأنسجة",
    "servicesPage.pathologyDesc": "تحليل خبير لعينات الأنسجة والخلايا للتشخيص الدقيق للأمراض بما في ذلك فحص السرطان.",
    "servicesPage.urinalysis": "تحليل البول والبراز",
    "servicesPage.urinalysisDesc": "تحليل روتيني وشامل لعينات البول والبراز لوظائف الكلى والعدوى وصحة الجهاز الهضمي.",
    "servicesPage.immunology": "المناعة والمصليات",
    "servicesPage.immunologyDesc": "فحوصات لوظائف الجهاز المناعي والحساسية وأمراض المناعة الذاتية.",
    "servicesPage.prenatal": "فحص ما قبل الولادة",
    "servicesPage.prenatalDesc": "فحوصات شاملة للأمهات الحوامل لضمان نتائج حمل صحية.",
    "servicesPage.drugMonitoring": "مراقبة الأدوية",
    "servicesPage.drugMonitoringDesc": "مراقبة الأدوية العلاجية وفحص السموم لإدارة الأدوية والسلامة.",
    "servicesPage.chemistry": "لوحة الكيمياء",
    "servicesPage.chemistryDesc": "لوحة استقلابية شاملة لتقييم وظائف الأعضاء والحالة الصحية العامة.",

    // Why Choose Us Page
    "whyPage.badge": "لماذا نحن",
    "whyPage.title": "التميز في كل فحص",
    "whyPage.description": "اكتشف لماذا يثق آلاف المرضى ومقدمي الرعاية الصحية في الأردن باسم المختبر الطبي لاحتياجاتهم التشخيصية.",
    "whyPage.isoAccredited": "مختبر معتمد من ISO",
    "whyPage.isoAccreditedDesc": "مختبرنا يلبي معايير الجودة الدولية، مما يضمن نتائج موثوقة ودقيقة يمكنك الوثوق بها.",
    "whyPage.fastTurnaround": "وقت استجابة سريع",
    "whyPage.fastTurnaroundDesc": "معظم نتائج الفحوصات متاحة خلال 24-48 ساعة، مما يساعدك أنت ومقدم الرعاية الصحية على اتخاذ قرارات في الوقت المناسب.",
    "whyPage.expertTeam": "فريق طبي خبير",
    "whyPage.expertTeamDesc": "أخصائيو أمراض معتمدون وفنيو مختبرات ذوو خبرة بسنوات من الخبرة في الفحص التشخيصي.",
    "whyPage.advancedTech": "تقنية متقدمة",
    "whyPage.advancedTechDesc": "أحدث معدات التشخيص والأنظمة الآلية تضمن نتائج دقيقة ومتسقة.",
    "whyPage.patientCentered": "رعاية تركز على المريض",
    "whyPage.patientCenteredDesc": "بيئة مريحة وترحيبية مع طاقم متعاطف مكرس لرفاهيتك.",
    "whyPage.experience": "+15 سنة من الخبرة",
    "whyPage.experienceDesc": "أكثر من عقد من الخدمة الموثوقة للمرضى ومقدمي الرعاية الصحية في جميع أنحاء الأردن.",
    "whyPage.yearsExp": "سنوات من الخبرة",
    "whyPage.testsYear": "فحص سنوياً",
    "whyPage.testTypes": "نوع فحص متاح",
    "whyPage.satisfaction": "رضا المرضى",
    "whyPage.commitmentBadge": "التزامنا",
    "whyPage.commitmentTitle": "صحتك هي أولويتنا",
    "whyPage.commitmentDesc": "في اسم المختبر الطبي، نتجاوز مجرد تقديم نتائج الفحوصات. نحن ملتزمون بدعم رحلتك الصحية بالتميز في كل خطوة.",
    "whyPage.commitment1": "دقة مضمونة مع بروتوكولات مراقبة الجودة",
    "whyPage.commitment2": "تعامل سري مع جميع معلومات المرضى",
    "whyPage.commitment3": "أسعار معقولة مع تكاليف شفافة",
    "whyPage.commitment4": "موقع مناسب في وسط عمان",
    "whyPage.commitment5": "ساعات عمل ممتدة لراحتك",
    "whyPage.commitment6": "شراكة مع مقدمي الرعاية الصحية الرائدين",
    "whyPage.visitTitle": "زرنا اليوم",
    "whyPage.location": "الموقع",
    "whyPage.workingHours": "ساعات العمل",
    "whyPage.workingHoursVal": "السبت-الخميس: 7ص-9م | الجمعة: 8ص-2م",

    // Contact Page
    "contact.badge": "اتصل بنا",
    "contact.title": "تواصل معنا",
    "contact.description": "هل لديك أسئلة حول خدماتنا؟ نحن هنا للمساعدة. تواصل معنا من خلال أي من القنوات أدناه.",
    "contact.infoTitle": "معلومات الاتصال",
    "contact.address": "العنوان",
    "contact.addressLine1": "123 الحي الطبي",
    "contact.addressLine2": "عمان، الأردن",
    "contact.phone": "الهاتف",
    "contact.phoneAvailable": "متاح خلال ساعات العمل",
    "contact.email": "البريد الإلكتروني",
    "contact.emailResponse": "نرد خلال 24 ساعة",
    "contact.workingHours": "ساعات العمل",
    "contact.hours1": "السبت - الخميس: 7:00 ص - 9:00 م",
    "contact.hours2": "الجمعة: 8:00 ص - 2:00 م",
    "contact.mapTitle": "موقع الخريطة",
    "contact.formTitle": "أرسل لنا رسالة",
    "contact.formDesc": "املأ النموذج أدناه وسنعود إليك في أقرب وقت ممكن.",
    "contact.fullName": "الاسم الكامل",
    "contact.fullNamePlaceholder": "أدخل اسمك الكامل",
    "contact.emailAddress": "البريد الإلكتروني",
    "contact.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "contact.phoneNumber": "رقم الهاتف",
    "contact.phonePlaceholder": "أدخل رقم هاتفك",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "كيف يمكننا مساعدتك؟",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.privacy": "نحترم خصوصيتك ولا نشارك معلوماتك أبداً.",
    "contact.successTitle": "تم إرسال الرسالة!",
    "contact.successDesc": "شكراً لتواصلك معنا. سنعود إليك قريباً.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  const isRTL = lang === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang, isRTL]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
