import { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.whyChoose": "Why Choose Us",
    "nav.contact": "Contact",
    "nav.getInTouch": "Get in Touch",
    "nav.labName": "One Lab Medical",
    "nav.tagline": "Precision Diagnostics",

    // Hero Section
    "hero.badge": "Trusted Medical Diagnostics",
    "hero.title": "Precision Lab Results You Can",
    "hero.titleHighlight": "Trust",
    "hero.description": "One Lab Medical Laboratories was founded in early 2021 to be a trusted reference in the field of medical laboratory services, placing quality and accuracy at the core of its mission. We combine advanced technology with expert care to deliver accurate diagnostic results.",
    "hero.viewServices": "View Our Services",
    "hero.fastResults": "Fast Results",
    "hero.fastResultsSub": "24-48 Hours",
    "hero.certifiedLab": "Certified Lab",
    "hero.certifiedLabSub": "ISO Accredited",
    "hero.expertTeam": "Expert Team",
    "hero.expertTeamSub": "15+ Years",

    // Services Preview
    "services.badge": "Our Services",
    "services.title": "Comprehensive Laboratory Services",
    "services.description": "One Lab receives samples from laboratories and hospitals, offering comprehensive laboratory services covering all specialties.",
    "services.viewAll": "View All Services",
    "services.bloodTests": "Blood Tests",
    "services.bloodTestsDesc": "Complete blood count, blood chemistry, and comprehensive panels.",
    "services.hormoneAnalysis": "Hormone Analysis",
    "services.hormoneAnalysisDesc": "Thyroid function, reproductive hormones, and metabolic hormone testing.",
    "services.diabetesScreening": "Diabetes Screening",
    "services.diabetesScreeningDesc": "Glucose testing, HbA1c monitoring, and insulin level assessments.",
    "services.pcrTesting": "PCR Testing",
    "services.pcrTestingDesc": "Advanced molecular diagnostics for infectious diseases.",
    "services.pathology": "Pathology",
    "services.pathologyDesc": "Tissue analysis, cytology, and histopathology services.",
    "services.generalDiagnostics": "General Diagnostics",
    "services.generalDiagnosticsDesc": "Routine laboratory examinations and check-ups.",

    // Why Choose Preview
    "whyChoose.badge": "Why Choose Us",
    "whyChoose.title": "Trusted by Thousands of Patients",
    "whyChoose.description": "We conduct over 1000 laboratory tests using the latest technologies, adhering to strict quality control systems and international standards to ensure the highest levels of accuracy and reliability in results.",
    "whyChoose.learnMore": "Learn More About Us",
    "whyChoose.accredited": "Accredited Laboratory",
    "whyChoose.accreditedDesc": "Strict quality control systems",
    "whyChoose.quickTurnaround": "Quick Turnaround",
    "whyChoose.quickTurnaroundDesc": "Fast and accurate results",
    "whyChoose.expertPathologists": "Expert Team",
    "whyChoose.expertPathologistsDesc": "Qualified nursing and lab staff",
    "whyChoose.patientCentered": "Patient-Centered Care",
    "whyChoose.patientCenteredDesc": "Your comfort and time are our priority",
    "whyChoose.yearsExperience": "Years Experience",
    "whyChoose.testsPerYear": "Tests Per Year",
    "whyChoose.testTypes": "Test Types",
    "whyChoose.accuracyRate": "Accuracy Rate",
    "whyChoose.commitment": "Committed to accuracy and patient satisfaction",

    // CTA Section
    "cta.title": "Need a Lab Test?",
    "cta.titleLine2": "We're Here to Help",
    "cta.description": "Visit our laboratory or contact us to learn more about our services. Our friendly staff is ready to assist you.",
    "cta.callUs": "Call Us Now",
    "cta.contactUs": "Contact Us",
    "cta.address": "Amman, Jordan",

    // Footer
    "footer.description": "Your trusted partner for accurate medical diagnostics and laboratory services.",
    "footer.quickLinks": "Quick Links",
    "footer.ourServices": "Our Services",
    "footer.contactUs": "Contact Us",
    "footer.copyright": "One Lab Medical. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.hours1": "Sat - Thu: 7:00 AM - 9:00 PM",
    "footer.hours2": "Friday: 8:00 AM - 2:00 PM",

    // About Page
    "about.badge": "About Us",
    "about.title": "Your Trusted Partner in Medical Diagnostics",
    "about.intro": "One Lab Medical Laboratories was founded in early 2021 to be a trusted reference in the field of medical laboratory services.",
    "about.storyBadge": "Our Story",
    "about.storyTitle": "A Legacy of Excellence",
    "about.storyP1": "Founded in early 2021, One Lab Medical began with a mission to be a trusted authority in medical laboratory services, placing quality and accuracy at the heart of its mission.",
    "about.storyP2": "We receive samples from laboratories and hospitals, providing comprehensive laboratory services covering all specialties.",
    "about.storyP3": "We perform over 1000 laboratory tests using state-of-the-art technologies, adhering to strict quality control systems and international standards that guarantee the highest levels of accuracy and reliability in results.",
    "about.modernFacility": "Modern Facility",
    "about.modernFacilityDesc": "Latest technologies",
    "about.expertTeam": "Expert Team",
    "about.expertTeamDesc": "Qualified professionals",
    "about.isoCertified": "Quality Control",
    "about.isoCertifiedDesc": "Strict quality systems",
    "about.missionTitle": "Our Mission",
    "about.missionText": "To provide high-quality and accurate laboratory services, ensuring the highest standards of reliability for our patients and partners.",
    "about.visionTitle": "Our Vision",
    "about.visionText": "To be the trusted reference in medical laboratory services, utilizing advanced technology and expert care.",
    "about.valuesBadge": "Our Values",
    "about.valuesTitle": "What Drives Us Every Day",
    "about.valuesDesc": "Quality, Accuracy, and Reliability are at the core of everything we do.",
    "about.accuracy": "Accuracy",
    "about.accuracyDesc": "Highest levels of accuracy in results.",
    "about.patientCare": "Patient Care",
    "about.patientCareDesc": "Your comfort is our priority.",
    "about.timeliness": "Timeliness",
    "about.timelinessDesc": "Fast and confidential results.",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "International standards of quality.",

    // Services Page
    "servicesPage.badge": "Our Services",
    "servicesPage.title": "Comprehensive Laboratory Services",
    "servicesPage.description": "We offer detailed laboratory services covering all specialties, performing over 1000 tests using the latest technologies.",
    "servicesPage.processBadge": "Simple Process",
    "servicesPage.processTitle": "How It Works",
    "servicesPage.processDesc": "Getting tested is quick and easy. Here's what to expect.",
    "servicesPage.step1": "Visit or Home Sampling",
    "servicesPage.step1Desc": "Visit us or request our home sampling service",
    "servicesPage.step2": "Sample Collection",
    "servicesPage.step2Desc": "Our qualified staff collects your sample carefully",
    "servicesPage.step3": "Lab Analysis",
    "servicesPage.step3Desc": "Analyzed using strict quality control systems",
    "servicesPage.step4": "Get Results",
    "servicesPage.step4Desc": "Fast and confidential results sent to you",
    
    // New Service Keys
    "servicesPage.premarital": "Premarital Tests",
    "servicesPage.premaritalDesc": "Essential tests required before marriage to ensure genetic compatibility and health.",
    "servicesPage.blood": "Blood Tests",
    "servicesPage.bloodDesc": "Comprehensive blood analysis for various health indicators.",
    "servicesPage.chemistry": "Routine & Special Chemistry",
    "servicesPage.chemistryDesc": "Detailed chemical analysis of body fluids for health assessment.",
    "servicesPage.semen": "Semen Analysis",
    "servicesPage.semenDesc": "Evaluation of sperm health and viability for fertility assessment.",
    "servicesPage.cancer": "Cancer Markers",
    "servicesPage.cancerDesc": "Screening and monitoring tests for various types of cancers.",
    "servicesPage.histopathology": "Histopathology & Tumor Markers",
    "servicesPage.histopathologyDesc": "Microscopic examination of tissue to study the manifestations of disease.",
    "servicesPage.virology": "Virology & Viral Load",
    "servicesPage.virologyDesc": "Detection and quantification of viruses including viral load testing.",
    "servicesPage.coagulation": "Coagulation Tests",
    "servicesPage.coagulationDesc": "Tests to measure your blood's ability to clot.",
    "servicesPage.hormones": "Hormone Tests",
    "servicesPage.hormonesDesc": "Comprehensive analysis of hormonal levels for body regulation.",
    "servicesPage.genetics": "Genetics & Hereditary Tests",
    "servicesPage.geneticsDesc": "DNA analysis to detect genetic disorders and hereditary conditions.",
    "servicesPage.foodSafety": "Food Safety Testing",
    "servicesPage.foodSafetyDesc": "Quality control testing for restaurants, hotels, and food factories.",

    // Packages Section
    "packages.badge": "Health Packages",
    "packages.title": "Comprehensive Health Packages",
    "packages.description": "One Lab offers accredited health packages at discounted prices compliant with Jordanian Ministry of Health regulations. Prepared to high quality standards, these packages meet individual needs for preventive care and comprehensive health monitoring.",
    "packages.bookNow": "Book Package",
    "packages.currency": "JOD",
    "packages.testsIncluded": "Tests Included:",

    // Home Sampling Section
    "homeSampling.title": "Home Sampling Service",
    "homeSampling.description": "To ensure your comfort and save your time, our laboratory offers home blood sampling service by qualified nursing staff, adhering to the highest standards of safety and accuracy. We reach you at your convenient time, carefully collect the sample, analyze it within the laboratory, and send the results quickly and with complete confidentiality.",
    "homeSampling.comfort": "Your comfort is our priority",
    "homeSampling.accuracy": "Accuracy and speed in results",
    "homeSampling.safety": "Full commitment to sterilization and safety standards",
    "homeSampling.bookNow": "Book Now",

    // Why Choose Us Page
    "whyPage.badge": "Why Choose Us",
    "whyPage.title": "Excellence in Every Test",
    "whyPage.description": "One Lab Medical Laboratories places quality and accuracy at the core of its message.",
    "whyPage.isoAccredited": "Strict Quality Control",
    "whyPage.isoAccreditedDesc": "We adhere to strict quality control systems and international standards.",
    "whyPage.fastTurnaround": "Fast Results",
    "whyPage.fastTurnaroundDesc": "We ensure speed and reliability in delivering your results.",
    "whyPage.expertTeam": "Qualified Staff",
    "whyPage.expertTeamDesc": "Our team uses the latest technologies and best practices.",
    "whyPage.advancedTech": "Latest Technologies",
    "whyPage.advancedTechDesc": "We use state-of-the-art technology for over 1000 lab tests.",
    "whyPage.patientCentered": "Patient Comfort",
    "whyPage.patientCenteredDesc": "We offer home sampling services for your convenience.",
    "whyPage.experience": "Founded 2021",
    "whyPage.experienceDesc": "Trusted reference in medical laboratory services since 2021.",
    "whyPage.yearsExp": "Years of Experience",
    "whyPage.testsYear": "Tests Per Year",
    "whyPage.testTypes": "Test Types Available",
    "whyPage.satisfaction": "Patient Satisfaction",
    "whyPage.commitmentBadge": "Our Commitment",
    "whyPage.commitmentTitle": "Quality and Accuracy",
    "whyPage.commitmentDesc": "Quality and accuracy are at the core of our mission at One Lab.",
    "whyPage.commitment1": "Strict quality control systems",
    "whyPage.commitment2": "Highest levels of accuracy and reliability",
    "whyPage.commitment3": "latest technologies used",
    "whyPage.commitment4": "Home sampling service available",
    "whyPage.commitment5": "Fast and confidential results",
    "whyPage.commitment6": "Comprehensive laboratory services",
    "whyPage.visitTitle": "Visit Us Today",
    "whyPage.location": "Location",
    "whyPage.workingHours": "Working Hours",
    "whyPage.workingHoursVal": "Sat-Thu: 7AM-9PM | Fri: 8AM-2PM",

    // Contact Page
    "contact.badge": "Contact Us",
    "contact.title": "Get in Touch",
    "contact.description": "For booking or inquiries, please contact us.",
    "contact.infoTitle": "Contact Information",
    "contact.address": "Address",
    "contact.addressLine1": "Amman",
    "contact.addressLine2": "Jordan",
    "contact.phone": "Phone",
    "contact.phoneAvailable": "Available during working hours",
    "contact.email": "Email",
    "contact.emailResponse": "We respond within 24 hours",
    "contact.workingHours": "Working Hours",
    "contact.hours1": "Saturday - Thursday: 7:00 AM - 9:00 PM",
    "contact.hours2": "Friday: 8:00 AM - 2:00 PM",
    "contact.mapTitle": "Map Location",
    "contact.formTitle": "Send us a Message",
    "contact.formDesc": "Fill out the form below and we'll get back to you as soon as possible.",
    "contact.fullName": "Full Name",
    "contact.fullNamePlaceholder": "Enter your full name",
    "contact.emailAddress": "Email Address",
    "contact.emailPlaceholder": "Enter your email address",
    "contact.phoneNumber": "Phone Number",
    "contact.phonePlaceholder": "Enter your phone number",
    "contact.message": "Message",
    "contact.messagePlaceholder": "How can we help you?",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.privacy": "We respect your privacy and never share your information.",
    "contact.successTitle": "Message Sent!",
    "contact.successDesc": "Thank you for contacting us. We'll get back to you soon.",
  },
  ar: {
    // Navbar
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.services": "خدماتنا",
    "nav.whyChoose": "لماذا نحن",
    "nav.contact": "اتصل بنا",
    "nav.getInTouch": "تواصل معنا",
    "nav.labName": "مختبر ون لاب الطبي",
    "nav.tagline": "تشخيص دقيق",

    // Hero Section
    "hero.badge": "تشخيصات طبية موثوقة",
    "hero.title": "نتائج مخبرية دقيقة يمكنك",
    "hero.titleHighlight": "الوثوق بها",
    "hero.description": "تأسست مختبرات ون لاب الطبية في مطلع عام 2021، لتكون مرجعًا موثوقًا في مجال الخدمات المخبرية الطبية، واضعةً الجودة والدقة في صميم رسالتها.",
    "hero.viewServices": "عرض خدماتنا",
    "hero.fastResults": "نتائج سريعة",
    "hero.fastResultsSub": "24-48 ساعة",
    "hero.certifiedLab": "مختبر معتمد",
    "hero.certifiedLabSub": "أنظمة ضبط جودة",
    "hero.expertTeam": "فريق خبير",
    "hero.expertTeamSub": "+15 سنة",

    // Services Preview
    "services.badge": "خدماتنا",
    "services.title": "خدمات مخبرية شاملة",
    "services.description": "تستقبل ون لاب العينات من المختبرات والمستشفيات، حيث تقدّم خدمات مخبرية شاملة تغطي جميع التخصصات.",
    "services.viewAll": "عرض جميع الخدمات",
    "services.bloodTests": "فحوصات الدم",
    "services.bloodTestsDesc": "فحوصات شاملة للدم وتحاليل دقيقة.",
    "services.hormoneAnalysis": "فحوصات الهرمونات",
    "services.hormoneAnalysisDesc": "تحليل دقيق لوظائف الهرمونات المختلفة.",
    "services.diabetesScreening": "فحوصات السكري",
    "services.diabetesScreeningDesc": "مراقبة دقيقة لمستويات السكر.",
    "services.pcrTesting": "فحوصات الفيروسات",
    "services.pcrTestingDesc": "تشخيصات متقدمة للفيروسات والتعددات الفيروسية.",
    "services.pathology": "فحوصات الأنسجة",
    "services.pathologyDesc": "تحليل الأنسجة والأورام بدقة عالية.",
    "services.generalDiagnostics": "التشخيصات العامة",
    "services.generalDiagnosticsDesc": "فحوصات روتينية وشاملة.",

    // Why Choose Preview
    "whyChoose.badge": "لماذا نحن",
    "whyChoose.title": "مرجع موثوق في الخدمات المخبرية",
    "whyChoose.description": "تُجري ون لاب أكثر من 1000 فحص مخبري باستخدام أحدث التقنيات، ووفق أنظمة ضبط جودة صارمة ومعايير دولية تضمن أعلى مستويات الدقة والموثوقية في النتائج.",
    "whyChoose.learnMore": "اعرف المزيد عنا",
    "whyChoose.accredited": "ضبط جودة صارم",
    "whyChoose.accreditedDesc": "معايير دولية تضمن الدقة",
    "whyChoose.quickTurnaround": "نتائج سريعة",
    "whyChoose.quickTurnaroundDesc": "دقة وسرعة في النتائج",
    "whyChoose.expertPathologists": "كادر مؤهل",
    "whyChoose.expertPathologistsDesc": "خبرات عالية في المجال",
    "whyChoose.patientCentered": "راحتك أولويتنا",
    "whyChoose.patientCenteredDesc": "خدمة السحب المنزلي متوفرة",
    "whyChoose.yearsExperience": "سنوات الخبرة",
    "whyChoose.testsPerYear": "فحص سنوياً",
    "whyChoose.testTypes": "نوع فحص",
    "whyChoose.accuracyRate": "نسبة الدقة",
    "whyChoose.commitment": "ملتزمون بالجودة والدقة",

    // CTA Section
    "cta.title": "هل تحتاج فحص مخبري؟",
    "cta.titleLine2": "نحن هنا لمساعدتك",
    "cta.description": "قم بزيارة مختبرنا أو تواصل معنا. للحجز أو الاستفسار، يرجى التواصل معنا.",
    "cta.callUs": "اتصل بنا الآن",
    "cta.contactUs": "تواصل معنا",
    "cta.address": "عمان، الأردن",

    // Footer
    "footer.description": "مرجعك الموثوق في مجال الخدمات المخبرية الطبية.",
    "footer.quickLinks": "روابط سريعة",
    "footer.ourServices": "خدماتنا",
    "footer.contactUs": "اتصل بنا",
    "footer.copyright": "مختبرات ون لاب الطبية. جميع الحقوق محفوظة.",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.hours1": "السبت - الخميس: 7:00 ص - 9:00 م",
    "footer.hours2": "الجمعة: 8:00 ص - 2:00 م",

    // About Page
    "about.badge": "من نحن",
    "about.title": "مرجع موثوق في الخدمات المخبرية الطبية",
    "about.intro": "تأسست مختبرات ون لاب الطبية في مطلع عام 2021، لتكون مرجعًا موثوقًا في مجال الخدمات المخبرية الطبية.",
    "about.storyBadge": "قصتنا",
    "about.storyTitle": "الجودة والدقة في صميم رسالتنا",
    "about.storyP1": "تأسست مختبرات ون لاب الطبية في مطلع عام 2021، لتكون مرجعًا موثوقًا في مجال الخدمات المخبرية الطبية، واضعةً الجودة والدقة في صميم رسالتها.",
    "about.storyP2": "تستقبل ون لاب العينات من المختبرات والمستشفيات، حيث تقدّم خدمات مخبرية شاملة تغطي جميع التخصصات.",
    "about.storyP3": "تُجري ون لاب أكثر من 1000 فحص مخبري باستخدام أحدث التقنيات، ووفق أنظمة ضبط جودة صارمة ومعايير دولية تضمن أعلى مستويات الدقة والموثوقية في النتائج.",
    "about.modernFacility": "أحدث التقنيات",
    "about.modernFacilityDesc": "تكنولوجيا متطورة",
    "about.expertTeam": "فريق مؤهل",
    "about.expertTeamDesc": "كادر ذو خبرة",
    "about.isoCertified": "ضبط الجودة",
    "about.isoCertifiedDesc": "معايير دولية صارمة",
    "about.missionTitle": "مهمتنا",
    "about.missionText": "أن نكون مرجعاً موثوقاً، واضعين الجودة والدقة في صميم رسالتنا لخدمة المرضى والمجتمع الطبي.",
    "about.visionTitle": "رؤيتنا",
    "about.visionText": "تقديم خدمات مخبرية شاملة بأعلى مستويات الدقة والموثوقية باستخدام أحدث التقنيات.",
    "about.valuesBadge": "قيمنا",
    "about.valuesTitle": "ما يحركنا كل يوم",
    "about.valuesDesc": "الجودة، الدقة، والموثوقية هي أساس عملنا.",
    "about.accuracy": "الدقة",
    "about.accuracyDesc": "أعلى مستويات الدقة والموثوقية في النتائج.",
    "about.patientCare": "راحتك أولويتنا",
    "about.patientCareDesc": "نسعى لراحتكم وتوفير وقتكم.",
    "about.timeliness": "السرعة",
    "about.timelinessDesc": "إرسال النتائج بسرعة وسرية تامة.",
    "about.excellence": "الجودة",
    "about.excellenceDesc": "أنظمة ضبط جودة صارمة.",

    // Services Page
    "servicesPage.badge": "خدماتنا",
    "servicesPage.title": "خدمات مخبرية شاملة",
    "servicesPage.description": "تُجري ون لاب أكثر من 1000 فحص مخبري باستخدام أحدث التقنيات، وتغطي جميع التخصصات.",
    "servicesPage.processBadge": "عملية بسيطة",
    "servicesPage.processTitle": "كيف تتم العملية",
    "servicesPage.processDesc": "إجراء الفحص سريع وسهل. إليك ما يمكن توقعه.",
    "servicesPage.step1": "زيارة المختبر أو السحب المنزلي",
    "servicesPage.step1Desc": "تفضل بزيارتنا أو اطلب خدمة السحب المنزلي",
    "servicesPage.step2": "جمع العينات",
    "servicesPage.step2Desc": "يتم سحب العينة بكل عناية من قبل كادر مؤهل",
    "servicesPage.step3": "التحليل المخبري",
    "servicesPage.step3Desc": "يتم التحليل داخل المختبر وفق أعلى المعايير",
    "servicesPage.step4": "استلام النتائج",
    "servicesPage.step4Desc": "إرسال النتائج بسرعة وسرية تامة",

    // New Service Keys - Arabic
    "servicesPage.premarital": "فحوصات ما قبل الزواج",
    "servicesPage.premaritalDesc": "فحوصات ضرورية للتأكد من التوافق الجيني والصحي.",
    "servicesPage.blood": "فحوصات الدم",
    "servicesPage.bloodDesc": "تحاليل شاملة للدم لتقييم الحالة الصحية.",
    "servicesPage.chemistry": "فحوصات الكيمياء الروتينية الخاصة",
    "servicesPage.chemistryDesc": "تحاليل كيميائية دقيقة للمساعدة في التشخيص.",
    "servicesPage.semen": "فحص السائل المنوي",
    "servicesPage.semenDesc": "تقييم الخصوبة وتحليل السائل المنوي.",
    "servicesPage.cancer": "فحوصات السرطانات",
    "servicesPage.cancerDesc": "الكشف المبكر ومتابعة الأورام السرطانية.",
    "servicesPage.histopathology": "فحوصات الأنسجة والأورام",
    "servicesPage.histopathologyDesc": "فحص دقيق للأنسجة لتشخيص الأمراض.",
    "servicesPage.virology": "فحوصات الفيروسات و التعددات الفيروسية",
    "servicesPage.virologyDesc": "الكشف عن الفيروسات وتحديد الحمل الفيروسي.",
    "servicesPage.coagulation": "فحوصات تجلطات الدم",
    "servicesPage.coagulationDesc": "تقييم قدرة الدم على التجلط.",
    "servicesPage.hormones": "فحوصات الهرمونات",
    "servicesPage.hormonesDesc": "تحليل شامل لمستويات الهرمونات في الجسم.",
    "servicesPage.genetics": "فحوصات الوراثة والجينات",
    "servicesPage.geneticsDesc": "فحوصات جينية لتشخيص الأمراض الوراثية.",
    "servicesPage.foodSafety": "fحوصات الرقابة الغذائية",
    "servicesPage.foodSafetyDesc": "للمطاعم والفنادق ومصانع الأغذية لضمان سلامة الغذاء.",

    // Packages Section
    "packages.badge": "الباقات الصحية",
    "packages.title": "باقات صحية شاملة",
    "packages.description": "يقدّم ون لاب باقات صحية معتمدة وبأسعار مخفّضة ضمن قوانين وزارة الصحة الأردنية ، تم إعدادها وفق معايير الجودة لتلبية احتياجات الأفراد في مجال الرعاية الوقائية والمتابعة الصحية الشاملة.",
    "packages.bookNow": "احجز الباقة",
    "packages.currency": "دينار",
    "packages.testsIncluded": "الفحوصات المشمولة:",

    // Home Sampling Section
    "homeSampling.title": "السحب المنزلي",
    "homeSampling.description": "حرصًا على راحتكم ووقتكم، يقدّم مختبرنا خدمة سحب عينات الدم من المنزل بواسطة كادر تمريضي مؤهل، وبأعلى معايير السلامة والدقة. نصل إليكم في الوقت المناسب لكم، ونقوم بسحب العينة بكل عناية، ثم يتم تحليلها داخل المختبر وإرسال النتائج بسرعة وسرية تامة.",
    "homeSampling.comfort": "راحتك أولويتنا",
    "homeSampling.accuracy": "دقة وسرعة في النتائج",
    "homeSampling.safety": "التزام كامل بمعايير التعقيم والسلامة",
    "homeSampling.bookNow": "احجز موعدك الآن",

    // Why Choose Us Page
    "whyPage.badge": "لماذا نحن",
    "whyPage.title": "التميز في كل فحص",
    "whyPage.description": "تأسست مختبرات ون لاب الطبية لتكون مرجعًا موثوقًا، واضعةً الجودة والدقة في صميم رسالتها.",
    "whyPage.isoAccredited": "ضبط جودة صارم",
    "whyPage.isoAccreditedDesc": "أنظمة ضبط جودة صارمة ومعايير دولية.",
    "whyPage.fastTurnaround": "نتائج سريعة",
    "whyPage.fastTurnaroundDesc": "نضمن أعلى مستويات الدقة والسرعة في النتائج.",
    "whyPage.expertTeam": "فريق خبير",
    "whyPage.expertTeamDesc": "كادر تمريضي ومخبري مؤهل.",
    "whyPage.advancedTech": "أحدث التقنيات",
    "whyPage.advancedTechDesc": "استخدام أحدث التقنيات لإجراء أكثر من 1000 فحص.",
    "whyPage.patientCentered": "راحة المريض",
    "whyPage.patientCenteredDesc": "نقدم خدمة السحب المنزلي لراحتكم.",
    "whyPage.experience": "تأسست 2021",
    "whyPage.experienceDesc": "مرجع موثوق في الخدمات المخبرية منذ 2021.",
    "whyPage.yearsExp": "سنوات من الخبرة",
    "whyPage.testsYear": "فحص سنوياً",
    "whyPage.testTypes": "نوع فحص متاح",
    "whyPage.satisfaction": "رضا المرضى",
    "whyPage.commitmentBadge": "التزامنا",
    "whyPage.commitmentTitle": "الجودة والدقة",
    "whyPage.commitmentDesc": "الجودة والدقة في صميم رسالتنا في ون لاب.",
    "whyPage.commitment1": "أنظمة ضبط جودة صارمة",
    "whyPage.commitment2": "أعلى مستويات الدقة والموثوقية",
    "whyPage.commitment3": "أحدث التقنيات المستخدمة",
    "whyPage.commitment4": "خدمة السحب المنزلي متوفرة",
    "whyPage.commitment5": "سرعة وسرية تامة في النتائج",
    "whyPage.commitment6": "خدمات مخبرية شاملة",
    "whyPage.visitTitle": "زرنا اليوم",
    "whyPage.location": "الموقع",
    "whyPage.workingHours": "ساعات العمل",
    "whyPage.workingHoursVal": "السبت-الخميس: 7ص-9م | الجمعة: 8ص-2م",
    
    // Contact Page
    "contact.badge": "اتصل بنا",
    "contact.title": "تواصل معنا",
    "contact.description": "للحجز أو الاستفسار، يرجى التواصل معنا.",
    "contact.infoTitle": "معلومات الاتصال",
    "contact.address": "العنوان",
    "contact.addressLine1": "عمان",
    "contact.addressLine2": "الأردن",
    "contact.phone": "الهاتف",
    "contact.phoneAvailable": "متاح خلال ساعات العمل",
    "contact.email": "البريد الإلكتروني",
    "contact.emailResponse": "نرد خلال 24 ساعة",
    "contact.workingHours": "ساعات العمل",
    "contact.hours1": "السبت - الخميس: 7:00 ص - 9:00 م",
    "contact.hours2": "الجمعة: 8:00 ص - 2:00 م",
    "contact.mapTitle": "موقع الخريطة",
    "contact.formTitle": "أرسل لنا رسالة",
    "contact.formDesc": "املأ النموذج أدناه وسنعود إليك في أقرب وقت ممكن.",
    "contact.fullName": "الاسم الكامل",
    "contact.fullNamePlaceholder": "أدخل اسمك الكامل",
    "contact.emailAddress": "البريد الإلكتروني",
    "contact.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "contact.phoneNumber": "رقم الهاتف",
    "contact.phonePlaceholder": "أدخل رقم هاتفك",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "كيف يمكننا مساعدتك؟",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.privacy": "نحترم خصوصيتك ولا نشارك معلوماتك أبداً.",
    "contact.successTitle": "تم إرسال الرسالة!",
    "contact.successDesc": "شكراً لتواصلك معنا. سنعود إليك قريباً.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[lang][key] || key;
  };

  const isRTL = lang === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang, isRTL]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
